services:

  switch:
    build: ./snmp
    container_name: virtual-switch
    expose:
      - "161/udp"
    networks:
      - monitoring
    volumes:
      - ./snmp/snmpd.conf:/etc/snmp/snmpd.conf

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    ports:
      - "9116:9116"

    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'

    volumes:
      - ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml
    
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
    external: true