global:

route:
  receiver: telegram

receivers:
  - name: telegram

    telegram_configs:
      - bot_token: "8641410491:AAHsI9W_Q1TusKokcvzPAuGiKcAFl8StuI0"

        chat_id: 2038203744

        parse_mode: HTML

        message: |
          🚨 <b>ALERTA DE REDE</b>

          <b>Nome:</b> {{ .CommonLabels.alertname }}

          <b>Severidade:</b> {{ .CommonLabels.severity }}

          <b>Descrição:</b>
          {{ .CommonAnnotations.description }}